In [ ]:
#Bibliotécas
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
#DataFrame
headers = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'salary']

df = pd.read_csv('adult.data.csv', names=headers)

In [ ]:
#Divisão em Parâmetro e Classe
X_df = df.iloc[:, 0:14].values
y_df = df.iloc[:, 14].values

In [ ]:
#LabelEncoder
labelencoder = LabelEncoder()
X_df[:, 1] = labelencoder.fit_transform(X_df[:, 1])
X_df[:, 3] = labelencoder.fit_transform(X_df[:, 3])
X_df[:, 5] = labelencoder.fit_transform(X_df[:, 5])
X_df[:, 6] = labelencoder.fit_transform(X_df[:, 6])
X_df[:, 7] = labelencoder.fit_transform(X_df[:, 7])
X_df[:, 8] = labelencoder.fit_transform(X_df[:, 8])
X_df[:, 9] = labelencoder.fit_transform(X_df[:, 9])
X_df[:, 13] = labelencoder.fit_transform(X_df[:, 13])
y_df = labelencoder.fit_transform(y_df)

In [ ]:
#One Hot Encoder
onehotencorder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1,3,5,6,7,8,9,13])], remainder='passthrough')
X_df = onehotencorder.fit_transform(X_df).toarray()

In [ ]:
#Standard Scaler
scaler = StandardScaler()
X_df = scaler.fit_transform(X_df)

In [ ]:
#Divisão df de treinamento e teste 15%
X_df_train, X_df_test, y_df_train, y_df_test =  train_test_split(X_df, y_df, test_size=0.15, random_state=0)

In [ ]:
print(X_df_train.shape, X_df_test.shape, y_df_train.shape, y_df_test.shape)

(27676, 108) (4885, 108) (27676,) (4885,)


In [ ]:
#kNN
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=10)
knn.fit(X_df_train, y_df_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [ ]:
predict_knn = knn.predict(X_df_test)

In [ ]:
accuracy_score(y_df_test, predict_knn)

0.8290685772773797

In [ ]:
confusion_matrix(y_df_test, predict_knn)

array([[3437,  256],
       [ 579,  613]])

In [ ]:
print(classification_report(y_df_test, predict_knn))

              precision    recall  f1-score   support

           0       0.86      0.93      0.89      3693
           1       0.71      0.51      0.59      1192

    accuracy                           0.83      4885
   macro avg       0.78      0.72      0.74      4885
weighted avg       0.82      0.83      0.82      4885



In [ ]:
#cross-validation
from sklern.model_selection import cross_val_score
result = cross_val_score(knn, X_df, y_df, cv = 10)

In [ ]:
#random forest
from sklearn.ensemble import RandomForestClassifier

In [ ]:
random_forest = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
random_forest.fit(X_df_train, y_df_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
predict_rf = random_forest.predict(X_df_test)

In [ ]:
accuracy_score(y_df_test, predict_rf)

0.8507676560900717

In [ ]:
confusion_matrix(y_df_test, predict_rf)

array([[3420,  273],
       [ 456,  736]])

In [ ]:
print(classification_report(y_df_test, predict_rf))

              precision    recall  f1-score   support

           0       0.88      0.93      0.90      3693
           1       0.73      0.62      0.67      1192

    accuracy                           0.85      4885
   macro avg       0.81      0.77      0.79      4885
weighted avg       0.85      0.85      0.85      4885



In [ ]:
#MLP
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
mlp_keras = Sequential()
mlp_keras.add(Dense(units=55, activation='relu', input_dim=108))
mlp_keras.add(Dense(units=55, activation='relu'))
mlp_keras.add(Dense(units=1, activation='sigmoid'))
mlp_keras.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
mlp_keras.fit(X_df_train, y_df_train, batch_size=10, epochs=100)

Epoch 1/100
2768/2768 [==============================] - 6s 2ms/step - loss: 0.3703 - accuracy: 0.8306
Epoch 2/100
2768/2768 [==============================] - 5s 2ms/step - loss: 0.3084 - accuracy: 0.8573
Epoch 3/100
2768/2768 [==============================] - 5s 2ms/step - loss: 0.3040 - accuracy: 0.8594
Epoch 4/100
2768/2768 [==============================] - 5s 2ms/step - loss: 0.2961 - accuracy: 0.8632
Epoch 5/100
2768/2768 [==============================] - 5s 2ms/step - loss: 0.2955 - accuracy: 0.8656
Epoch 6/100
2768/2768 [==============================] - 5s 2ms/step - loss: 0.2893 - accuracy: 0.8656
Epoch 7/100
2768/2768 [==============================] - 5s 2ms/step - loss: 0.2884 - accuracy: 0.8668
Epoch 8/100
2768/2768 [==============================] - 5s 2ms/step - loss: 0.2789 - accuracy: 0.8723
Epoch 9/100
2768/2768 [==============================] - 5s 2ms/step - loss: 0.2796 - accuracy: 0.8741
Epoch 10/100
2768/2768 [==============================] - 5s 2ms/step - l

In [ ]:
predict_mlp_keras = mlp_keras.predict(X_df_test)

In [ ]:
predict_mlp_keras = (predict_mlp_keras > 0.5)

In [ ]:
accuracy_score(y_df_test, predict_mlp_keras)

0.8184237461617195

In [ ]:
confusion_matrix(y_df_test, predict_mlp_keras)

array([[3253,  440],
       [ 447,  745]])

In [ ]:
print(classification_report(y_df_test, predict_mlp_keras ))

              precision    recall  f1-score   support

           0       0.88      0.88      0.88      3693
           1       0.63      0.62      0.63      1192

    accuracy                           0.82      4885
   macro avg       0.75      0.75      0.75      4885
weighted avg       0.82      0.82      0.82      4885



In [ ]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(verbose=True, max_iter=1000, tol=0.000010, hidden_layer_sizes=(100, 100))
mlp.fit(X_df_train, y_df_train)

Iteration 1, loss = 0.37552725
Iteration 2, loss = 0.32181706
Iteration 3, loss = 0.30995593
Iteration 4, loss = 0.30173559
Iteration 5, loss = 0.29670519
Iteration 6, loss = 0.29233434
Iteration 7, loss = 0.28840006
Iteration 8, loss = 0.28529671
Iteration 9, loss = 0.28273772
Iteration 10, loss = 0.27971318
Iteration 11, loss = 0.27620812
Iteration 12, loss = 0.27424059
Iteration 13, loss = 0.27142015
Iteration 14, loss = 0.26943867
Iteration 15, loss = 0.26610260
Iteration 16, loss = 0.26464183
Iteration 17, loss = 0.26078358
Iteration 18, loss = 0.25974695
Iteration 19, loss = 0.25698770
Iteration 20, loss = 0.25382001
Iteration 21, loss = 0.25205727
Iteration 22, loss = 0.24866301
Iteration 23, loss = 0.24665569
Iteration 24, loss = 0.24369740
Iteration 25, loss = 0.24259023
Iteration 26, loss = 0.24023257
Iteration 27, loss = 0.23674159
Iteration 28, loss = 0.23614613
Iteration 29, loss = 0.23387445
Iteration 30, loss = 0.23239805
Iteration 31, loss = 0.22969525
Iteration 32, los

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100, 100), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=1e-05, validation_fraction=0.1, verbose=True,
              warm_start=False)

In [ ]:
predict_mlp = mlp.predict(X_df_test)

In [ ]:
accuracy_score(y_df_test, predict_mlp)

0.8073694984646879

In [ ]:
confusion_matrix(y_df_test, predict_mlp)

array([[3245,  448],
       [ 493,  699]])

In [ ]:
print(classification_report(y_df_test, predict_mlp))

              precision    recall  f1-score   support

           0       0.87      0.88      0.87      3693
           1       0.61      0.59      0.60      1192

    accuracy                           0.81      4885
   macro avg       0.74      0.73      0.74      4885
weighted avg       0.80      0.81      0.81      4885

